version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://neondb_owner:npg_5DYNKOvEXRI3@ep-aged-base-a1wt41l2-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-jwt-secret-here
      PORT: 8080
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
  redis_data:
