import { Exam } from "@/types/exam.type";

export const exam: Exam = {
  JEE: {
    exam_id: "JEE",
    exam_name: "JEE Main (BE/BTech) – Official Pattern",
    total_questions: 75,
    total_marks: 300,
    duration_mins: 180,
    marking_scheme: {
      marks_per_correct: 4,
      marks_per_wrong: -1,
      marks_per_unattempt: 0,
    },
    subjects: [
      {
        id: "fdee61f5-0236-44d2-b614-a1da45659ca6",
        name: "Physics",
        share_percentage: 33.3333,
        fixed_questions: 25,
        avg_time_per_question_in_secs: 120,
        difficulty_distribution: {
          easy_pct: 30.0,
          medium_pct: 45.0,
          hard_pct: 20.0,
          very_hard_pct: 5.0,
        },
        question_type_weights: {
          CALCULATION: 0.25,
          APPLICATION: 0.2,
          THEORETICAL: 0.1,
          TRICKY: 0.05,
          FACTUAL: 0.05,
          TRAP: 0.02,
          MULTI_STEP: 0.1,
          OUT_OF_THE_BOX: 0.01,
          ELIMINATION_BASED: 0.05,
          MEMORY_BASED: 0.02,
          CONFIDENCE_BASED: 0.0,
          HIGH_WEIGHTAGE: 0.05,
          CONCEPTUAL: 0.15,
          FORMULA_BASED: 0.2,
        },
      },
      {
        id: "959f2ce7-b37a-4325-a9d0-d46c2ba3ef59",
        name: "Chemistry",
        share_percentage: 33.3333,
        fixed_questions: 25,
        avg_time_per_question_in_secs: 120,
        difficulty_distribution: {
          easy_pct: 35.0,
          medium_pct: 45.0,
          hard_pct: 15.0,
          very_hard_pct: 5.0,
        },
        question_type_weights: {
          CALCULATION: 0.15,
          APPLICATION: 0.15,
          THEORETICAL: 0.15,
          TRICKY: 0.05,
          FACTUAL: 0.1,
          TRAP: 0.02,
          MULTI_STEP: 0.05,
          OUT_OF_THE_BOX: 0.01,
          ELIMINATION_BASED: 0.05,
          MEMORY_BASED: 0.1,
          CONFIDENCE_BASED: 0.0,
          HIGH_WEIGHTAGE: 0.03,
          CONCEPTUAL: 0.1,
          FORMULA_BASED: 0.2,
        },
      },
      {
        id: "c47c9c14-2dd7-42fc-823d-d3f550a0e471",
        name: "Mathematics",
        share_percentage: 33.3333,
        fixed_questions: 25,
        avg_time_per_question_in_secs: 120,
        difficulty_distribution: {
          easy_pct: 25.0,
          medium_pct: 50.0,
          hard_pct: 20.0,
          very_hard_pct: 5.0,
        },
        question_type_weights: {
          CALCULATION: 0.3,
          APPLICATION: 0.2,
          THEORETICAL: 0.1,
          TRICKY: 0.05,
          FACTUAL: 0.05,
          TRAP: 0.02,
          MULTI_STEP: 0.1,
          OUT_OF_THE_BOX: 0.01,
          ELIMINATION_BASED: 0.05,
          MEMORY_BASED: 0.02,
          CONFIDENCE_BASED: 0.0,
          HIGH_WEIGHTAGE: 0.05,
          CONCEPTUAL: 0.15,
          FORMULA_BASED: 0.2,
        },
      },
    ],
    global_difficulty_bias: {
      easy_pct: 30.0,
      medium_pct: 45.0,
      hard_pct: 20.0,
      very_hard_pct: 5.0,
    },
    constraints: {
      min_subject_questions: 5,
      max_subject_questions: 40,
      min_difficulty_questions_per_subject: 2,
    },
  },
  NEET: {
    exam_id: "NEET",
    exam_name: "NEET (UG) - Official 2025 Pattern (filled)",
    total_questions: 180,
    total_marks: 720,
    duration_mins: 180,
    marking_scheme: {
      marks_per_correct: 4,
      marks_per_wrong: -1,
      marks_per_unattempt: 0,
    },
    subjects: [
      {
        id: "fdee61f5-0236-44d2-b614-a1da45659ca6",
        name: "Physics",
        share_percentage: 25.0,
        fixed_questions: 45,
        avg_time_per_question_in_secs: 100,
        difficulty_distribution: {
          easy_pct: 40.0,
          medium_pct: 40.0,
          hard_pct: 15.0,
          very_hard_pct: 5.0,
        },
        question_type_weights: {
          CALCULATION: 0.3,
          APPLICATION: 0.2,
          THEORETICAL: 0.1,
          TRICKY: 0.05,
          FACTUAL: 0.05,
          TRAP: 0.03,
          GUESS_BASED: 0.01,
          MULTI_STEP: 0.1,
          OUT_OF_THE_BOX: 0.02,
          ELIMINATION_BASED: 0.05,
          MEMORY_BASED: 0.02,
          CONFIDENCE_BASED: 0.0,
          HIGH_WEIGHTAGE: 0.05,
          CONCEPTUAL: 0.2,
          FORMULA_BASED: 0.25,
        },
      },
      {
        id: "959f2ce7-b37a-4325-a9d0-d46c2ba3ef59",
        name: "Chemistry",
        share_percentage: 25.0,
        min_questions: 45,
        max_questions: 45,
        fixed_questions: 45,
        avg_time_per_question_in_secs: 70,
        difficulty_distribution: {
          easy_pct: 40.0,
          medium_pct: 40.0,
          hard_pct: 15.0,
          very_hard_pct: 5.0,
        },
        question_type_weights: {
          CALCULATION: 0.15,
          APPLICATION: 0.1,
          THEORETICAL: 0.1,
          TRICKY: 0.05,
          FACTUAL: 0.2,
          TRAP: 0.03,
          GUESS_BASED: 0.01,
          MULTI_STEP: 0.05,
          OUT_OF_THE_BOX: 0.02,
          ELIMINATION_BASED: 0.05,
          MEMORY_BASED: 0.1,
          CONFIDENCE_BASED: 0.0,
          HIGH_WEIGHTAGE: 0.05,
          CONCEPTUAL: 0.1,
          FORMULA_BASED: 0.2,
        },
      },
      {
        id: "70821584-88d7-4205-9f32-4dd5ecde20b9",
        name: "Biology",
        share_percentage: 50.0,
        min_questions: 90,
        max_questions: 90,
        fixed_questions: 90,
        avg_time_per_question_in_secs: 40,
        difficulty_distribution: {
          easy_pct: 45.0,
          medium_pct: 40.0,
          hard_pct: 12.0,
          very_hard_pct: 3.0,
        },
        question_type_weights: {
          CALCULATION: 0.0,
          APPLICATION: 0.15,
          THEORETICAL: 0.25,
          TRICKY: 0.05,
          FACTUAL: 0.25,
          TRAP: 0.02,
          GUESS_BASED: 0.02,
          MULTI_STEP: 0.05,
          OUT_OF_THE_BOX: 0.01,
          ELIMINATION_BASED: 0.05,
          MEMORY_BASED: 0.1,
          CONFIDENCE_BASED: 0.0,
          HIGH_WEIGHTAGE: 0.03,
          CONCEPTUAL: 0.2,
          FORMULA_BASED: 0.0,
        },
      },
    ],
    global_difficulty_bias: {
      easy_pct: 40.0,
      medium_pct: 40.0,
      hard_pct: 17.0,
      very_hard_pct: 3.0,
    },
    constraints: {
      min_subject_questions: 10,
      max_subject_questions: 120,
      min_difficulty_questions_per_subject: 2,
    },
  },
};
