export const filterData = {
  JEE:{
    Physics:[
      "Physical World and Measurement",
      "Kinematics",
      "Laws of Motion",
      "Work, Energy, and Power",
      "System of Particles and Rotational Motion",
      "Gravitation",
      "Mechanical Properties of Solids and Fluids",
      "Thermal Properties of Matter",
      "Thermodynamics",
      "Kinetic Theory of Gases",
      "Oscillations and Waves",
      "Electrostatics",
      "Current Electricity",
      "Magnetic Effects of Current and Magnetism",
      "Electromagnetic Induction and Alternating Currents",
      "Electromagnetic Waves",
      "Optics",
      "Dual Nature of Matter and Radiation",
      "Atoms and Nuclei",
      "Electronic Devices",
      "Communication Systems"
    ],
    Chemistry:[
      "Basic Concepts of Chemistry",
      "Structure of Atom",
      "Classification of Elements and Periodicity in Properties",
      "Chemical Bonding and Molecular Structure",
      "States of Matter",
      "Thermodynamics",
      "Equilibrium",
      "Redox Reactions",
      "The s-Block Element",
      "The p-Block Elements",
      "Hydrocarbons",
      "Environmental Chemistry",
      "Solid State",
      "Solutions",
      "Electrochemistry",
      "Chemical Kinetics",
      "Surface Chemistry",
      "The p-Block Elements",
      "The d- and f-Block Elements",
      "Coordination Compounds",
      "Haloalkanes and Haloarenes",
      "Alcohols, Phenols, and Ethers",
      "Aldehydes, Ketones, and Carboxylic Acids",
      "Amines",
      "Biomolecules",
      "Polymers",
      "Chemistry in Everyday Life"
  
    ],
    Mathematics:[
      "Sets, Relations, and Functions",
      "Complex Numbers and Quadratic Equations",
      "Matrices and Determinants",
      "Permutations and Combinations",
      "Mathematical Induction",
      "Binomial Theorem",
      "Sequences and Series",
      "Co-ordinate Geometry",
      "Straight Lines",
      "Conic Sections",
      "Trigonometry",
      "Limits and Derivatives",
      "Statistics and Probability",
      "Relations and Functions",
      "Inverse Trigonometric Functions",
      "Matrices and Determinants",
      "Continuity and Differentiability",
      "Application of Derivatives",
      "Integrals",
      "Application of Integrals",
      "Differential Equations",
      "Vector Algebra",
      "Three Dimensional Geometry",
      "Linear Programming",
      "Probability",
    ]
  },
  NEET:{
    Physics:[
      "Physical World and Measurement",
      "Kinematics",
      "Laws of Motion",
      "Work, Energy, and Power",
      "System of Particles and Rotational Motion",
      "Gravitation",
      "Mechanical Properties of Solids and Fluids",
      "Thermal Properties of Matter",
      "Thermodynamics",
      "Kinetic Theory of Gases",
      "Oscillations and Waves",
      "Electrostatics",
      "Current Electricity",
      "Magnetic Effects of Current and Magnetism",
      "Electromagnetic Induction and Alternating Currents",
      "Electromagnetic Waves",
      "Optics",
      "Dual Nature of Matter and Radiation",
      "Atoms and Nuclei",
      "Electronic Devices",
      "Communication Systems"
    ],
    Chemistry:[
      "Basic Concepts of Chemistry",
      "Structure of Atom",
      "Classification of Elements and Periodicity in Properties",
      "Chemical Bonding and Molecular Structure",
      "States of Matter",
      "Thermodynamics",
      "Equilibrium",
      "Redox Reactions",
      "The s-Block Element",
      "The p-Block Elements",
      "Hydrocarbons",
      "Environmental Chemistry",
      "Solid State",
      "Solutions",
      "Electrochemistry",
      "Chemical Kinetics",
      "Surface Chemistry",
      "The p-Block Elements",
      "The d- and f-Block Elements",
      "Coordination Compounds",
      "Haloalkanes and Haloarenes",
      "Alcohols, Phenols, and Ethers",
      "Aldehydes, Ketones, and Carboxylic Acids",
      "Amines",
      "Biomolecules",
      "Polymers",
      "Chemistry in Everyday Life"
    ],
    Biology:[
      "The Living World ",
      "Biological Classification",
      "Plant Kingdom",
      "Animal Kingdom",
      "Morphology Of Flowering Plant",
      "Anatomy Of Flowering Plant",
      "Structural Organisation In Animals",
      "Cell: The Unit Of Life",
      "Biomolecules",
      "Cell Cycle And Cell Division",
      "Photosynthesis In Higher Plant",
      "Respiration In Plant",
      "Plant Growth And Development",
      "Breathing And Exchange Of Gases",
      "Body Fluid And Circulation",
      "Excretory Products And Their Elimination",
      "Locomotion And Movement",
      "neural control And Coordination ",
      "Chemical Coordination And Integration",
      "Sexual Reproduction In Flowering Plant",
      "Human Reproduction",
      "Reproductive Health",
      "Principles Of Inheritance And Variation",
      "Molecular Basis Of Inheritance",
      "Evolution",
      "Human Health And Disease",
      "Microbes In Human Welfare",
      "Biotechnology: Principles And Processes",
      "Biotechnology And Its Application",
      "Organisms And Populations",
      "Ecosystem",
      "Biodiversity And Conservation"
    ]
  }
}

export const topics = [
    "Default",
    "Physical World and Measurement",
    "Kinematics",
    "Laws of Motion",
    "Work, Energy, and Power",
    "System of Particles and Rotational Motion",
    "Gravitation",
    "Mechanical Properties of Solids and Fluids",
    "Thermal Properties of Matter",
    "Thermodynamics",
    "Kinetic Theory of Gases",
    "Oscillations and Waves",
    "Electrostatics",
    "Current Electricity",
    "Magnetic Effects of Current and Magnetism",
    "Electromagnetic Induction and Alternating Currents",
    "Electromagnetic Waves",
    "Optics",
    "Dual Nature of Matter and Radiation",
    "Atoms and Nuclei",
    "Electronic Devices",
    "Communication Systems",
    "Basic Concepts of Chemistry",
    "Atomic Structure",
    "Classification of Elements and Periodicity in Properties",
    "Chemical Bonding and Molecular Structure",
    "States of Matter",
    "Thermodynamics",
    "Equilibrium",
    "Redox Reactions",
    "The s-Block Element",
    "The p-Block Elements",
    "Hydrocarbons",
    "Environmental Chemistry",
    "Solid State",
    "Solutions",
    "Electrochemistry",
    "Chemical Kinetics",
    "Surface Chemistry",
    "The p-Block Elements",
    "The d- and f-Block Elements",
    "Coordination Compounds",
    "Haloalkanes and Haloarenes",
    "Alcohols, Phenols, and Ethers",
    "Aldehydes, Ketones, and Carboxylic Acids",
    "Amines",
    "Biomolecules",
    "Polymers",
    "Chemistry in Everyday Life",
    "Sets, Relations, and Functions",
    "Complex Numbers and Quadratic Equations",
    "Matrices and Determinants",
    "Permutations and Combinations",
    "Mathematical Induction",
    "Binomial Theorem",
    "Sequences and Series",
    "Straight Lines",
    "Conic Sections",
    "Trigonometry",
    "Limits and Derivatives",
    "Statistics and Probability",
    "Relations and Functions",
    "Inverse Trigonometric Functions",
    "Matrices and Determinants",
    "Continuity and Differentiability",
    "Application of Derivatives",
    "Integrals",
    "Application of Integrals",
    "Differential Equations",
    "Vector Algebra",
    "Three Dimensional Geometry",
    "Linear Programming",
    "Probability",
    "Other",
  ];
