export enum QuestionFormat {
  SINGLE_SELECT = "SINGLE_SELECT",
  MULTIPLE_SELECT = "MULTIPLE_SELECT",
  TRUE_FALSE = "TRUE_FALSE",
  MATCHING = "MATCHING",
  ASSERTION_REASON = "ASSERTION_REASON",
  COMPREHENSION = "COMPREHENSION",
  MATRIX_MATCH = "MATRIX_MATCH",
}
