name: Deploy and Run Prisma Migrations

on:
  push:
    branches:
      - main # Replace with your production branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      # Step 3: Install npm Dependencies
      - name: Install dependencies
        run: |
          cd packages/db
          npm install
          cd ../..

      # Step 4: Install Vercel CLI
      - name: Install Vercel CLI
        run: npm install -g vercel

      # Step 5: Run Prisma Migrations
      - name: Run Prisma Migrations
        run: |
          cd packages/db
          npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Step 6: Deploy to Vercel
      - name: Deploy to Vercel
        run: |
          vercel --prod --yes --name "rank-marg-10" --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
